CREATE DATABASE IF NOT EXISTS TEMP;
USE TEMP;
CREATE TABLE STUDENT(
 ID INT PRIMARY KEY,
 NAME VARCHAR(50),
 AGE INT NOT NULL,
 primary KEY (NAME)
 );
 CREATE TABLE temp(
 c_ID INT,
 foreign key(c_ID) references student(id)
 );
 INSERT INTO STUDENT VALUES
 (1,"SHRUTI",26),
 (2,"SEEMA",24)
 ;
 SELECT * FROM STUDENT;
 INSERT INTO STUDENT VALUES
 (3,"SHRUTI",26),
 (4,"SEEMA",24)
 ;
