import tkinter as tk;
root=tk.Tk()
def say_hello(l2):
    l2.config(text="form submitted")
root.title("first gui screen")
root.resizable(False, False)
root.geometry("700x400")
root.iconphoto(False, tk.PhotoImage(file=r"D:\js in depth\newfile\Screenshot 2025-10-25 201639.png"))
root.configure(bg="lightblue")
label = tk.Label(root, text="Hello, Tkinter!",bg="lightpink",font=("Arial", 16, "bold"), fg="darkblue")   # <-- Widget
label.pack(side="top",pady=20)
photo = tk.PhotoImage(file=r"D:\js in depth\newfile\Screenshot 2025-10-25 201639.png")
# label.grid(row=2,column=1)
l1 = tk.Label(root, image=photo)
l1.pack()
main_frame = tk.Frame(root, bg="lightpink", padx=20, pady=20)
main_frame.pack(pady=30) 
name=tk.Label(main_frame,text="Name",bg="lightpink",font=("Arial", 13, "bold"), fg="darkblue")
name.grid(row=0, column=0)
item=tk.Entry(main_frame,width=50)
item.grid(row=0,column=1)
email=tk.Label(main_frame,text="email",bg="lightpink",font=("Arial", 13, "bold"), fg="darkblue")
email.grid(row=1, column=0)
item=tk.Entry(main_frame,width=50)
item.grid(row=1,column=1)
l2=tk.Label(main_frame,text="",bg="pink",fg="blue",font=("Arial", 13, "bold"))
l2.grid(row=2,column=2)
btn=tk.Button(main_frame, text="Submit", bg="lightblue", fg="darkblue",
                       font=("Arial", 12, "bold") ,command=lambda:say_hello(l2))
btn.grid(pady=10,row=2,column=1)
root.mainloop()
